# Let's call MSVS 2017 the default compiler, 64 bit the default architecture,
# release the default configuration and --enable-shared the default mode.
#
# Build jobs
#  1. six basic builds: 32/64bit on MSVS2013/2015/2017
#  2. add static lib, amalgamation and debug on MSVC2017
#
# Note: Avoid the AppVeyor settings `platform` and `configuration` since excluding
# from the build matrix is not supported (https://github.com/appveyor/ci/issues/386)

clone_depth: 5

environment:
  matrix:
    # 1
    - MSVS: 2013
      PLATFORM: x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - MSVS: 2013
      PLATFORM: x86_amd64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - MSVS: 2015
      PLATFORM: x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - MSVS: 2015
      PLATFORM: x86_amd64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - MSVS: 2017
      PLATFORM: x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - MSVS: 2017
      PLATFORM: x86_amd64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    # 2
    - MSVS: 2017
      PLATFORM: x86_amd64
      CONFIG: --disable-shared
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - MSVS: 2017
      PLATFORM: x86_amd64
      CONFIG: --amalgamation
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    # 3
    - MSVS: 2017
      PLATFORM: x86_amd64
      CONFIG: --with-debug
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

install:
  - call src\scripts\ci\setup_appveyor.bat

build_script:
  - call src\scripts\ci\build_appveyor.bat

# whitelist branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
    - master
    - release-2
    - phone-ci
